joystick_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [4]          # RB button on Xbox Series S|X controller
      require_enable_button: true   # This ensures values reset to zero when deadman button is released
      axis_mappings:
        linear-x:                   # Forward/Backward movement
          axis: 1                   # Left stick vertical axis
          scale: 0.5
          offset: 0.0
        linear-y:                   # Left/Right strafe
          axis: 0                   # Left stick horizontal axis
          scale: 0.5
          offset: 0.0
        angular-z:                  # Yaw rotation (turning in place)
          axis: 3                   # Right stick horizontal axis
          scale: 0.5
          offset: 0.0
